2023-11-20 09:31:29,010 ERROR: Exception on /index [GET] [in C:\Py\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Flasky\app\routes.py", line 33, in index
    return render_template('index.html',title='Home',form=form,posts=posts.items, next_url=next_url, prev_url=prev_url, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Py\Flasky\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Py\Flasky\app\templates\base.html", line 48, in top-level template code
    {% block scripts %}
  File "C:\Py\Flasky\app\templates\base.html", line 49, in block 'scripts'
    {{ super() }}
  File "C:\Py\venv\Lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2023-11-20 21:43:41,853 INFO: Flasky startup [in C:\Py\Flasky\app\__init__.py:54]
2023-11-20 22:10:19,610 INFO: Flasky startup [in C:\Py\Flasky\app\__init__.py:55]
2023-11-21 08:57:55,091 INFO: Flasky startup [in C:\Py\Flasky\app\__init__.py:55]
2023-11-21 09:01:01,441 INFO: Flasky startup [in C:\Py\Flasky\app\__init__.py:55]
2023-11-21 09:01:03,408 ERROR: Exception on /explore [GET] [in C:\Py\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Flasky\app\routes.py", line 47, in explore
    return render_template('index.html',title='Explore', posts=posts.items,next_url=next_url, prev_url=prev_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Py\Flasky\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Py\Flasky\app\templates\base.html", line 18, in top-level template code
    {% block navbar %}
  File "C:\Py\Flasky\app\templates\base.html", line 25, in block 'navbar'
    {{ _('%(home_link)s') }}
  File "C:\Py\venv\Lib\site-packages\jinja2\ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\jinja2\ext.py", line 179, in gettext
    return rv % variables  # type: ignore
           ~~~^~~~~~~~~~~
  File "C:\Py\venv\Lib\site-packages\markupsafe\__init__.py", line 115, in __mod__
    return self.__class__(super().__mod__(arg))
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\markupsafe\__init__.py", line 272, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
                               ~~~~~~~~^^^^^^
KeyError: 'home_link'
2023-11-21 09:01:20,261 INFO: Flasky startup [in C:\Py\Flasky\app\__init__.py:55]
2023-11-21 09:01:22,305 ERROR: Exception on /explore [GET] [in C:\Py\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\Flasky\app\routes.py", line 47, in explore
    return render_template('index.html',title='Explore', posts=posts.items,next_url=next_url, prev_url=prev_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Py\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Py\Flasky\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Py\Flasky\app\templates\base.html", line 18, in top-level template code
    {% block navbar %}
  File "C:\Py\Flasky\app\templates\base.html", line 25, in block 'navbar'
    {{ _('%(home_link)s') }}
  File "C:\Py\venv\Lib\site-packages\jinja2\ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\jinja2\ext.py", line 179, in gettext
    return rv % variables  # type: ignore
           ~~~^~~~~~~~~~~
  File "C:\Py\venv\Lib\site-packages\markupsafe\__init__.py", line 115, in __mod__
    return self.__class__(super().__mod__(arg))
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Py\venv\Lib\site-packages\markupsafe\__init__.py", line 272, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
                               ~~~~~~~~^^^^^^
KeyError: 'home_link'
